/*
  stock_time_series.g.dart – Auto-generated JSON serialization

  • _$TimePriceFromJson(Map<String, dynamic> json) → TimePrice:
      – Reads `timestamp` (as int) and `price` (as double) from the JSON map
      – Returns a new TimePrice(timestamp: …, price: …)

  • _$TimePriceToJson(TimePrice instance) → Map<String, dynamic>:
      – Serializes `timestamp` and `price` fields from TimePrice back into a JSON map

  • _$StockTimeSeriesFromJson(Map<String, dynamic> json) → StockTimeSeries:
      – Reads the `points` array and maps each entry through TimePrice.fromJson
      – Reads `latestPrice` and converts it to double
      – Constructs a StockTimeSeries(points: …, latestPrice: …)

  • _$StockTimeSeriesToJson(StockTimeSeries instance) → Map<String, dynamic>:
      – Serializes the `points` list (each is a TimePrice, so it uses its toJson)
      – Serializes `latestPrice` back into the JSON map

  ⚠️ These methods are generated by `json_serializable`.
     Do NOT modify by hand; rerun the build_runner if the model changes.
*/

part of 'stock_time_series.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TimePrice _$TimePriceFromJson(Map<String, dynamic> json) => TimePrice(
      timestamp: (json['timestamp'] as num).toInt(),
      price: (json['price'] as num).toDouble(),
    );

Map<String, dynamic> _$TimePriceToJson(TimePrice instance) => <String, dynamic>{
      'timestamp': instance.timestamp,
      'price': instance.price,
    };

StockTimeSeries _$StockTimeSeriesFromJson(Map<String, dynamic> json) =>
    StockTimeSeries(
      points: (json['points'] as List<dynamic>)
          .map((e) => TimePrice.fromJson(e as Map<String, dynamic>))
          .toList(),
      latestPrice: (json['latestPrice'] as num).toDouble(),
    );

Map<String, dynamic> _$StockTimeSeriesToJson(StockTimeSeries instance) =>
    <String, dynamic>{
      'points': instance.points,
      'latestPrice': instance.latestPrice,
    };
